name: Laravel CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.3'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Python dependencies
      run: |
        cd infra
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Start infrastructure
      run: |
        cd infra/docker
        python3 orchestrator.py start --no-wait

    - name: Wait for services
      run: sleep 30

    - name: Run PHP tests
      run: make test

    - name: Run PHP linters
      run: make lint

    - name: Run Pint fix
      run: make pint

    - name: Stop infrastructure
      run: |
        cd infra/docker
        python3 orchestrator.py stop

    - name: Notify Slack on Failure
      if: failure()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}